sudo: required

dist: trusty

language: c

compiler:
   - gcc

services:
  - docker

env:
  - TARGET=LINUX VLC_VERSION=2.1
  - TARGET=LINUX VLC_VERSION=2.2
  - TARGET=WINDOWS VLC_VERSION=2.1
  - TARGET=WINDOWS VLC_VERSION=2.2

before_script:
  - if [ "$TARGET" = "LINUX" ] && [ "$VLC_VERSION" = "2.2" ]; then sudo add-apt-repository ppa:mc3man/trusty-media -y; fi
  - sudo apt-get update -qq
  - if [ "$TARGET" = "LINUX" ]; then sudo apt-get install vlc pkg-config libvlccore-dev -qq; fi
  - if [ "$TARGET" = "WINDOWS" ]; then sudo apt-get install tree -qq; fi
  - if [ "$TARGET" = "WINDOWS" ]; then sudo docker build -t vlc-pause-click-plugin-windows-build docker ; fi

script:
  - if [ "$TARGET" = "LINUX" ]; then sudo make install; fi
  - if [ "$TARGET" = "WINDOWS" ]; then sudo docker run --rm -v `pwd`:/repo -v `pwd`/build:/build vlc-pause-click-plugin-windows-build $VLC_VERSION i686; fi
  - if [ "$TARGET" = "WINDOWS" ]; then sudo docker run --rm -v `pwd`:/repo -v `pwd`/build:/build vlc-pause-click-plugin-windows-build $VLC_VERSION x86_64; fi
  - if [ "$TARGET" = "WINDOWS" ]; then tree build -s --si --du; fi
  - if [ "$TARGET" = "WINDOWS" ] && [ $(find ./build -name "*.dll" | wc -l) != "2" ]; then false; fi
